# Generated by Django 5.1.1 on 2024-09-13 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_product_discounted_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CR', 'Curd'), ('ML', 'Milk'), ('LS', 'Lassi'), ('MS', 'Milkshake'), ('PN', 'Paneer'), ('GH', 'Ghee'), ('IC', 'Icecreams'), ('CZ', 'Cheese')], max_length=2),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('mobile', models.IntegerField(default=0)),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(choices=[('Nairobi', 'Nairobi'), ('Mombasa', 'Mombasa'), ('Kisumu', 'Kisumu'), ('Nakuru', 'Nakuru'), ('Kiambu', 'Kiambu'), ('Nyeri', 'Nyeri'), ('Murang’a', 'Murang’a'), ('Kirinyaga', 'Kerugoya'), ('Embu', 'Embu'), ('Machakos', 'Machakos'), ('Kitui', 'Kitui'), ('Makueni', 'Wote'), ('Meru', 'Meru'), ('Tharaka Nithi', 'Chuka'), ('Isiolo', 'Isiolo'), ('Marsabit', 'Marsabit'), ('Garissa', 'Garissa'), ('Wajir', 'Wajir'), ('Mandera', 'Mandera'), ('Tana River', 'Hola'), ('Lamu', 'Lamu'), ('Kilifi', 'Kilifi'), ('Taita Taveta', 'Voi'), ('Kwale', 'Kwale'), ('Turkana', 'Lodwar'), ('West Pokot', 'Kapenguria'), ('Samburu', 'Mararal'), ('Trans Nzoia', 'Kitale'), ('Uasin Gishu', 'Eldoret'), ('Elgeyo Marakwet', 'Iten'), ('Nandi', 'Kapsabet'), ('Baringo', 'Kabarnet'), ('Laikipia', 'Rumuruti'), ('Narok', 'Narok'), ('Kajiado', 'Kajiado'), ('Kericho', 'Kericho'), ('Bomet', 'Bomet'), ('Kakamega', 'Kakamega'), ('Vihiga', 'Vihiga'), ('Bungoma', 'Bungoma'), ('Busia', 'Busia'), ('Siaya', 'Siaya'), ('Homa Bay', 'Homa Bay'), ('Migori', 'Migori'), ('Kisii', 'Kisii'), ('Nyamira', 'Nyamira')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
